import React from 'react';
import ScrollReveal from './ScrollReveal';

const TermsOfService: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  return (
    <section className="pt-40 pb-24 bg-background min-h-screen">
      <div className="container mx-auto px-6 max-w-4xl">
        <ScrollReveal>
          <button 
            onClick={onBack}
            className="flex items-center gap-2 text-brand font-bold text-xs uppercase tracking-widest mb-12 hover:translate-x-[-4px] transition-transform"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7" />
            </svg>
            Return to Home
          </button>
          
          <h1 className="text-4xl md:text-6xl font-heading font-bold text-primary mb-6 tracking-tight">Terms of Service</h1>
          <p className="text-slateText/60 font-sans text-sm mb-12 uppercase tracking-[0.2em]">Last Updated: October 24, 2023</p>

          <div className="prose prose-slate max-w-none space-y-8 text-slateText leading-relaxed">
            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">1. Acceptance of Terms</h2>
              <p>By accessing or using the Vayuk Solutions website and services, you agree to be bound by these Terms of Service and all applicable laws and regulations in Canada. If you do not agree with any of these terms, you are prohibited from using or accessing this site.</p>
            </div>

            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">2. Description of Services</h2>
              <p>Vayuk Solutions provides AI-driven digital transformation, custom software development, and automation consulting primarily for Small and Medium Enterprises (SMEs). All insights provided by our "AI Optimizer" or "ROI Calculator" are for informational purposes and do not constitute a guarantee of business results.</p>
            </div>

            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">3. AI Tool Disclaimer</h2>
              <p>Our website features an AI-powered ROI analyzer. By using this tool, you acknowledge that:</p>
              <ul className="list-disc pl-6 mt-4 space-y-2">
                <li>The results are generated by an Artificial Intelligence model (Google Gemini).</li>
                <li>The data provided is an estimate based on your input and should not be used as the sole basis for business decisions.</li>
                <li>Vayuk Solutions is not liable for any discrepancies between AI-projected ROI and actual business performance.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">4. Intellectual Property</h2>
              <p>The content, logo, graphics, and software code on this website are the intellectual property of Vayuk Solutions. You may not reproduce, distribute, or create derivative works without our express written consent.</p>
            </div>

            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">5. Limitation of Liability</h2>
              <p>In no event shall Vayuk Solutions, its directors, or its employees be liable for any indirect, incidental, special, or consequential damages arising out of the use of our automation tools or consulting services. Our total liability is limited to the amount paid by the client for the specific service in question.</p>
            </div>

            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">6. Governing Law</h2>
              <p>These terms and conditions are governed by and construed in accordance with the <strong>laws of the Province of Ontario and the federal laws of Canada</strong> applicable therein. You irrevocably submit to the exclusive jurisdiction of the courts in that Province.</p>
            </div>

            <div>
              <h2 className="text-2xl font-heading font-bold text-accent mb-4">7. Changes to Terms</h2>
              <p>Vayuk Solutions reserves the right to revise these terms at any time without notice. By using this website, you are agreeing to be bound by the then-current version of these Terms of Service.</p>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default TermsOfService;